import ErrorDisplay from "../components/ErrorDisplay"
import Navigation from "../components/navigation"
import { ErrorProvider } from "./contexts/ErrorContext"
import "../styles/global.css"

export const metadata = {
  title: {
    templrate : "%s | Next Movies",
    default : "Next Movies",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}

        </body>
    </html>
  )
}
